//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAprilClientBezKolbaka.SRRegistracijaVozila {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAprilBeKalbaka")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAprilBeKalbaka")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAprilClientBezKolbaka.SRRegistracijaVozila.RegistrovanVlasnik))]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrovanVlasnik", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAprilBeKalbaka")]
    [System.SerializableAttribute()]
    public partial class RegistrovanVlasnik : WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRRegistracijaVozila.IRegistracijaVozila")]
    public interface IRegistracijaVozila {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/Register", ReplyAction="http://tempuri.org/IRegistracijaVozila/RegisterResponse")]
        void Register(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo vo, WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik vl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/Register", ReplyAction="http://tempuri.org/IRegistracijaVozila/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo vo, WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik vl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetVlasniciModela", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetVlasniciModelaResponse")]
        System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik> GetVlasniciModela(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetVlasniciModela", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetVlasniciModelaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik>> GetVlasniciModelaAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetVozilaForVlasnik", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetVozilaForVlasnikResponse")]
        System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo> GetVozilaForVlasnik(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetVozilaForVlasnik", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetVozilaForVlasnikResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo>> GetVozilaForVlasnikAsync(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetSvaVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetSvaVozilaResponse")]
        System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo> GetSvaVozila();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/GetSvaVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/GetSvaVozilaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo>> GetSvaVozilaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaVozilaChannel : WcfAprilClientBezKolbaka.SRRegistracijaVozila.IRegistracijaVozila, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaVozilaClient : System.ServiceModel.ClientBase<WcfAprilClientBezKolbaka.SRRegistracijaVozila.IRegistracijaVozila>, WcfAprilClientBezKolbaka.SRRegistracijaVozila.IRegistracijaVozila {
        
        public RegistracijaVozilaClient() {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo vo, WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik vl) {
            base.Channel.Register(vo, vl);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo vo, WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik vl) {
            return base.Channel.RegisterAsync(vo, vl);
        }
        
        public System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik> GetVlasniciModela(string model) {
            return base.Channel.GetVlasniciModela(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik>> GetVlasniciModelaAsync(string model) {
            return base.Channel.GetVlasniciModelaAsync(model);
        }
        
        public System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo> GetVozilaForVlasnik(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik v) {
            return base.Channel.GetVozilaForVlasnik(v);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo>> GetVozilaForVlasnikAsync(WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vlasnik v) {
            return base.Channel.GetVozilaForVlasnikAsync(v);
        }
        
        public System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo> GetSvaVozila() {
            return base.Channel.GetSvaVozila();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAprilClientBezKolbaka.SRRegistracijaVozila.Vozilo>> GetSvaVozilaAsync() {
            return base.Channel.GetSvaVozilaAsync();
        }
    }
}
