//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppExactTime.ServiceReferenceExactTime {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceExactTime.IServiceExactTime")]
    public interface IServiceExactTime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExactTime/GetExactTime", ReplyAction="http://tempuri.org/IServiceExactTime/GetExactTimeResponse")]
        System.DateTime GetExactTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExactTime/GetExactTime", ReplyAction="http://tempuri.org/IServiceExactTime/GetExactTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetExactTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExactTimeChannel : WindowsFormsAppExactTime.ServiceReferenceExactTime.IServiceExactTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExactTimeClient : System.ServiceModel.ClientBase<WindowsFormsAppExactTime.ServiceReferenceExactTime.IServiceExactTime>, WindowsFormsAppExactTime.ServiceReferenceExactTime.IServiceExactTime {
        
        public ServiceExactTimeClient() {
        }
        
        public ServiceExactTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExactTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExactTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExactTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetExactTime() {
            return base.Channel.GetExactTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetExactTimeAsync() {
            return base.Channel.GetExactTimeAsync();
        }
    }
}
