//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClientApril2021.ServiceReferenceRegistracijaVozila {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/WcfApril2021")]
    [System.SerializableAttribute()]
    public partial class Vehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://schemas.datacontract.org/2004/07/WcfApril2021")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClientApril2021.ServiceReferenceRegistracijaVozila.RegisteredOwner))]
    public partial class Owner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisteredOwner", Namespace="http://schemas.datacontract.org/2004/07/WcfApril2021")]
    [System.SerializableAttribute()]
    public partial class RegisteredOwner : WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRegistracijaVozila.IRegVozila", CallbackContract=typeof(WCFClientApril2021.ServiceReferenceRegistracijaVozila.IRegVozilaCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRegVozila {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/Register")]
        void Register(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle v, WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/Register")]
        System.Threading.Tasks.Task RegisterAsync(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle v, WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwnerVehicles")]
        void GetOwnerVehicles(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwnerVehicles")]
        System.Threading.Tasks.Task GetOwnerVehiclesAsync(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwners")]
        void GetOwners(string model, string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwners")]
        System.Threading.Tasks.Task GetOwnersAsync(string model, string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetAllVehicles")]
        void GetAllVehicles(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetAllVehicles")]
        System.Threading.Tasks.Task GetAllVehiclesAsync(string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegVozilaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwnerVehiclesResponse")]
        void GetOwnerVehiclesResponse(System.Collections.Generic.List<WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle> vehicles);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetOwnersResponse")]
        void GetOwnersResponse(System.Collections.Generic.List<WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner> owners);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegVozila/GetAllVehiclesResponse")]
        void GetAllVehiclesResponse(System.Collections.Generic.List<WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle> vehicles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegVozilaChannel : WCFClientApril2021.ServiceReferenceRegistracijaVozila.IRegVozila, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegVozilaClient : System.ServiceModel.DuplexClientBase<WCFClientApril2021.ServiceReferenceRegistracijaVozila.IRegVozila>, WCFClientApril2021.ServiceReferenceRegistracijaVozila.IRegVozila {
        
        public RegVozilaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RegVozilaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RegVozilaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RegVozilaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RegVozilaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Register(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle v, WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o) {
            base.Channel.Register(v, o);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Vehicle v, WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o) {
            return base.Channel.RegisterAsync(v, o);
        }
        
        public void GetOwnerVehicles(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o) {
            base.Channel.GetOwnerVehicles(o);
        }
        
        public System.Threading.Tasks.Task GetOwnerVehiclesAsync(WCFClientApril2021.ServiceReferenceRegistracijaVozila.Owner o) {
            return base.Channel.GetOwnerVehiclesAsync(o);
        }
        
        public void GetOwners(string model, string user) {
            base.Channel.GetOwners(model, user);
        }
        
        public System.Threading.Tasks.Task GetOwnersAsync(string model, string user) {
            return base.Channel.GetOwnersAsync(model, user);
        }
        
        public void GetAllVehicles(string user) {
            base.Channel.GetAllVehicles(user);
        }
        
        public System.Threading.Tasks.Task GetAllVehiclesAsync(string user) {
            return base.Channel.GetAllVehiclesAsync(user);
        }
    }
}
