//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppLoto2020.SRLoto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kombinacija", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceJun2020")]
    [System.SerializableAttribute()]
    public partial class Kombinacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> VrednostiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> Vrednosti {
            get {
                return this.VrednostiField;
            }
            set {
                if ((object.ReferenceEquals(this.VrednostiField, value) != true)) {
                    this.VrednostiField = value;
                    this.RaisePropertyChanged("Vrednosti");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rezultat", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceJun2020")]
    [System.SerializableAttribute()]
    public partial class Rezultat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeticeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SedmiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SesticeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Petice {
            get {
                return this.PeticeField;
            }
            set {
                if ((this.PeticeField.Equals(value) != true)) {
                    this.PeticeField = value;
                    this.RaisePropertyChanged("Petice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sedmice {
            get {
                return this.SedmiceField;
            }
            set {
                if ((this.SedmiceField.Equals(value) != true)) {
                    this.SedmiceField = value;
                    this.RaisePropertyChanged("Sedmice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sestice {
            get {
                return this.SesticeField;
            }
            set {
                if ((this.SesticeField.Equals(value) != true)) {
                    this.SesticeField = value;
                    this.RaisePropertyChanged("Sestice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cestitka", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceJun2020")]
    [System.SerializableAttribute()]
    public partial class Cestitka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppLoto2020.SRLoto.Kombinacija PobednickaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SadrzajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleAppLoto2020.SRLoto.Kombinacija Pobednicka {
            get {
                return this.PobednickaField;
            }
            set {
                if ((object.ReferenceEquals(this.PobednickaField, value) != true)) {
                    this.PobednickaField = value;
                    this.RaisePropertyChanged("Pobednicka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sadrzaj {
            get {
                return this.SadrzajField;
            }
            set {
                if ((object.ReferenceEquals(this.SadrzajField, value) != true)) {
                    this.SadrzajField = value;
                    this.RaisePropertyChanged("Sadrzaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRLoto.ILoto", CallbackContract=typeof(ConsoleAppLoto2020.SRLoto.ILotoCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILoto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/DodajKombinaciju", ReplyAction="http://tempuri.org/ILoto/DodajKombinacijuResponse")]
        int DodajKombinaciju(string nick, ConsoleAppLoto2020.SRLoto.Kombinacija kombinacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/DodajKombinaciju", ReplyAction="http://tempuri.org/ILoto/DodajKombinacijuResponse")]
        System.Threading.Tasks.Task<int> DodajKombinacijuAsync(string nick, ConsoleAppLoto2020.SRLoto.Kombinacija kombinacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/UkloniKombinaciju", ReplyAction="http://tempuri.org/ILoto/UkloniKombinacijuResponse")]
        int UkloniKombinaciju(string nick, long kombinacijaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/UkloniKombinaciju", ReplyAction="http://tempuri.org/ILoto/UkloniKombinacijuResponse")]
        System.Threading.Tasks.Task<int> UkloniKombinacijuAsync(string nick, long kombinacijaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/KreniIzvlacenje", ReplyAction="http://tempuri.org/ILoto/KreniIzvlacenjeResponse")]
        void KreniIzvlacenje(string sifra, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoto/KreniIzvlacenje", ReplyAction="http://tempuri.org/ILoto/KreniIzvlacenjeResponse")]
        System.Threading.Tasks.Task KreniIzvlacenjeAsync(string sifra, int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILotoCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoto/ProsledjivanjeBroja")]
        void ProsledjivanjeBroja(int broj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoto/KrajIzvlacenja")]
        void KrajIzvlacenja(ConsoleAppLoto2020.SRLoto.Rezultat rezultat);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoto/ProsledjivanjeCestitke")]
        void ProsledjivanjeCestitke(ConsoleAppLoto2020.SRLoto.Cestitka cestitka);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILotoChannel : ConsoleAppLoto2020.SRLoto.ILoto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotoClient : System.ServiceModel.DuplexClientBase<ConsoleAppLoto2020.SRLoto.ILoto>, ConsoleAppLoto2020.SRLoto.ILoto {
        
        public LotoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LotoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LotoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LotoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LotoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int DodajKombinaciju(string nick, ConsoleAppLoto2020.SRLoto.Kombinacija kombinacija) {
            return base.Channel.DodajKombinaciju(nick, kombinacija);
        }
        
        public System.Threading.Tasks.Task<int> DodajKombinacijuAsync(string nick, ConsoleAppLoto2020.SRLoto.Kombinacija kombinacija) {
            return base.Channel.DodajKombinacijuAsync(nick, kombinacija);
        }
        
        public int UkloniKombinaciju(string nick, long kombinacijaID) {
            return base.Channel.UkloniKombinaciju(nick, kombinacijaID);
        }
        
        public System.Threading.Tasks.Task<int> UkloniKombinacijuAsync(string nick, long kombinacijaID) {
            return base.Channel.UkloniKombinacijuAsync(nick, kombinacijaID);
        }
        
        public void KreniIzvlacenje(string sifra, int value) {
            base.Channel.KreniIzvlacenje(sifra, value);
        }
        
        public System.Threading.Tasks.Task KreniIzvlacenjeAsync(string sifra, int value) {
            return base.Channel.KreniIzvlacenjeAsync(sifra, value);
        }
    }
}
