//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsCisterna.SRCisterna {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materijal", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOktobar2020")]
    [System.SerializableAttribute()]
    public partial class Materijal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GustinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZapreminaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gustina {
            get {
                return this.GustinaField;
            }
            set {
                if ((this.GustinaField.Equals(value) != true)) {
                    this.GustinaField = value;
                    this.RaisePropertyChanged("Gustina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Masa {
            get {
                return this.MasaField;
            }
            set {
                if ((this.MasaField.Equals(value) != true)) {
                    this.MasaField = value;
                    this.RaisePropertyChanged("Masa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Zapremina {
            get {
                return this.ZapreminaField;
            }
            set {
                if ((this.ZapreminaField.Equals(value) != true)) {
                    this.ZapreminaField = value;
                    this.RaisePropertyChanged("Zapremina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRCisterna.ICisterna", CallbackContract=typeof(WindowsFormsCisterna.SRCisterna.ICisternaCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICisterna {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICisterna/DodajMaterijal")]
        void DodajMaterijal(WindowsFormsCisterna.SRCisterna.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICisterna/DodajMaterijal")]
        System.Threading.Tasks.Task DodajMaterijalAsync(WindowsFormsCisterna.SRCisterna.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICisterna/IsipajMaterijal")]
        void IsipajMaterijal(decimal zapremina);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICisterna/IsipajMaterijal")]
        System.Threading.Tasks.Task IsipajMaterijalAsync(decimal zapremina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/TrenutnoStanje", ReplyAction="http://tempuri.org/ICisterna/TrenutnoStanjeResponse")]
        WindowsFormsCisterna.SRCisterna.Materijal TrenutnoStanje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/TrenutnoStanje", ReplyAction="http://tempuri.org/ICisterna/TrenutnoStanjeResponse")]
        System.Threading.Tasks.Task<WindowsFormsCisterna.SRCisterna.Materijal> TrenutnoStanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Promene", ReplyAction="http://tempuri.org/ICisterna/PromeneResponse")]
        System.Collections.Generic.List<string> Promene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/Promene", ReplyAction="http://tempuri.org/ICisterna/PromeneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICisterna/NotifyStanje")]
        void NotifyStanje(bool puna);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaChannel : WindowsFormsCisterna.SRCisterna.ICisterna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisternaClient : System.ServiceModel.DuplexClientBase<WindowsFormsCisterna.SRCisterna.ICisterna>, WindowsFormsCisterna.SRCisterna.ICisterna {
        
        public CisternaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CisternaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CisternaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void DodajMaterijal(WindowsFormsCisterna.SRCisterna.Materijal m) {
            base.Channel.DodajMaterijal(m);
        }
        
        public System.Threading.Tasks.Task DodajMaterijalAsync(WindowsFormsCisterna.SRCisterna.Materijal m) {
            return base.Channel.DodajMaterijalAsync(m);
        }
        
        public void IsipajMaterijal(decimal zapremina) {
            base.Channel.IsipajMaterijal(zapremina);
        }
        
        public System.Threading.Tasks.Task IsipajMaterijalAsync(decimal zapremina) {
            return base.Channel.IsipajMaterijalAsync(zapremina);
        }
        
        public WindowsFormsCisterna.SRCisterna.Materijal TrenutnoStanje() {
            return base.Channel.TrenutnoStanje();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsCisterna.SRCisterna.Materijal> TrenutnoStanjeAsync() {
            return base.Channel.TrenutnoStanjeAsync();
        }
        
        public System.Collections.Generic.List<string> Promene() {
            return base.Channel.Promene();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PromeneAsync() {
            return base.Channel.PromeneAsync();
        }
    }
}
